[options]
addons_path = /mnt/extra-addons
admin_passwd = $pbkdf2-sha512$600000$9n5PaU1JaQ2BUOp9j9FaSw$WhdXVu95GFqfEVH2aM7RqA226aCsUUQnWUaxo4KbYrNVw8LxYPIytan5oKZ6GmkI8MdkxzqpIoMq9MB4zhc12w
dbfilter = .*
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo

